### ISSUE TITLE
clicking on adjacent thumbnails continously and rapidly before one animation ends makes main slideshow div blank

### ISSUE THREAD

**Issue by salgaonkarayush** [sylouuu/desoslide#26]
Hi sir,

First of all thanks for such a wonderful plugin.

I have noticed small issue while clicking on adjacent thumbnails or any 2 thumbnails continuously and rapidly
Issue pops up on documentation demo page too.
http://sylouuu.github.io/desoslide/doc/demo.html

While debugging I found that if animation fadein or fadeOut is not complete, 
class: fadeOut remains stuck. 

// inspected code below for example 2
div id="slideshow2" class="col-lg-12">
div class="desoslide-wrapper">
<img alt="Rose" class="img-responsive animated fadeOut" 

while inspecting image element on chrome developer tool i noticed that
if i check and un-check (i.e toggle checkbox) class in Chrome Developer tool > style panel - 
.fadeOut{
-webkit-animation-name:fadeOut
}

Things start working properly again.

Then what i have done to resolve this 
currently i have initialize plugin with effect: 'none'
and now when someone clicks on thumbnail i am making its opacity 1, coz when we are not using effect and generate same issue #slideshow1 .desoslide-wrapper img opacity gets stuck to 0, this hides main image.

//neo-slide bug workaround
		$('.slideshow1_thumbs a').click(function(){
			$('#slideshow1 .desoslide-wrapper img').css('opacity', 1 );
			}); 
			//neo-slide bug workaround fix ends 

Now what i m looking for is permanent solution to  fix this bug for effects too

**Comment by sylouuu** [comment]
Hi,

I've no time to fix this. You have to keep your workaround. Sorry.

Regards
