### ISSUE TITLE
Simple jQuery based animation without a 50 kb provider?

### ISSUE THREAD

**Issue by pwFoo** [sylouuu/desoslide#28]
Hi,

looked at desoslider and really like it! 

Because provider adds 50kb (animate.css) or 35kb (magic.css) size. 
Is it possible to use "simple single animation type like fade / slide without a additional provider?

**Comment by sylouuu** [comment]
Hi @pwFoo,

Glad to hear you liked desoSlide!

According to the [documentation](http://sylouuu.github.io/desoslide/doc/), you can get an instant transition without including a provider file with:

```js
$('#slideshow').desoSlide('setEffect', 'none');
```

But you will not have a basic transition such as `fadeIn/fadeOut`.

Bests

**Comment by pwFoo** [comment]
Hi @sylouuu 

thanks for your reply. 
So there isn't a plan to have minimal basic transitions without animation / magic provider?
I think a minimal basic provider would be great addition to desoSlide!


Regards

**Comment by sylouuu** [comment]
I have no plan for adding features to desoSlide, only fixes.

In case you want to get smaller files as possible, download the non-minified version of the provider, remove the effects you don't need and reminify. :)

Bests
