### ISSUE TITLE
IE9+IE10 problem with 2.2.0

### ISSUE THREAD

**Issue by pwFoo** [sylouuu/desoslide#31]
Hello,

I tested the latest code (js and css both version 2.2.0) and also your demo http://sylouuu.github.io/desoslide/doc/demo.html without success.

The slideshow is missing with IE <= 10 the slideshow is missing. Also read issue #23 before. 

Should DesoSlide 2.2.0 support IE 9+10 or should I downgrade to an older version?

**Comment by sylouuu** [comment]
Hello,

The linked demo works on my IE11, if I emulate IE10 and IE9 it's still OK but IE8 throws an error relatives to a package using to the demo page, not related to the desoSlide core code.

Do you have an error or something?

Bests

**Comment by pwFoo** [comment]
No popup error with IE9, just the slideshow is missing (thumbnails left / right are fine).
IE10 shows "Your browser is too old!" message and two popup error messages (translated):

1. line 1, char 5960, method not supported
2. line 1, char 231, 'Array.prototype.map is NULL or not an object'

Get the same messages with IE10 and IE8, but not IE9...?

Tested with IE-Tester (http://www.my-debugbar.com/wiki/IETester/HomePage)

**Comment by sylouuu** [comment]
Try with the official emulate tool inside IE10/11 developer console.

**Comment by pwFoo** [comment]
Thanks, works with the IE developer tools. Looks like IE-tester isn't reliable anymore...
