### ISSUE TITLE
Slow Fade Effect

### ISSUE THREAD

**Issue by tobias-bruns** [sylouuu/desoslide#32]
Hello,

is there a way to make the fade effect faster (not the interval)? Here are my settings:

```js
$('#slideshow').desoSlide({
  thumbs: $('#slideshow_thumbs li > a'),
  auto: {
    start: true
  },
  first: 1,
  interval: 4000,
  effect: {
    provider: 'animate',
    name: 'fade'
  },
});
```

**Comment by sylouuu** [comment]
Hi @tobias-bruns,

This question has been already answered [here](https://github.com/sylouuu/desoslide/issues/18#issuecomment-41409526). (ref. #18).

Bests
