### ISSUE TITLE
Desoslide attr data-desoslide-index

### ISSUE THREAD

**Issue by DSergioD** [sylouuu/desoslide#33]
I have one problem, i want attr "data-desoslide-index" from thumb a-tag to have with same value on the image in "desoslide-wrapper" image. I tried everything but it's useless.
So, this .attr('data-' + self._namespace + '-index', i); on the "desoslide-wrapper" image.Is this possible ?

I want to have on the thumbs class active, now on the click is not a problem, problem is if image automatic play on desoslide wrapper, or if go to next or previous.So i think that i cant do this if image on desoslide-wrapper and thumbs have connection like data-desoslide-index.

**Comment by sylouuu** [comment]
Hello @DSergioD,

Actually you want to know which thumb is currently "active", displayed?

**Comment by JonathanVandal** [comment]
Hello, I'd like to know how to get the current active thumb to grab the thumbs alt when I click on the thumb.

Actually I got the event : 
```
$('#slideshow').on('thumbClick.desoslide', function(e) {
    
});
```

And how I can get the thumb information 

```
$('#slideshow').desoSlide('getThumbs', x);
```

But I don't how to get the thumbs index when I click. I hope you can help me

**Comment by sylouuu** [comment]
Hi @JonathanVandal 

```js
$('#slideshow').on('thumbClick.desoslide', function(e) {
    console.log(e);
});
```

Do you get something printed?

Otherwise, there is no way to retrieve the current thumb, excepts if you want to fork the source code. It's a very old source code that I don't maintain anymore, but I think you may start right there: https://github.com/sylouuu/desoslide/blob/master/src/js/jquery.desoslide.js#L1023

Best

**Comment by JonathanVandal** [comment]
Hi thank you for you answer.
Too bad if you don't maintain this project :( it's very hard to find a good slideshow library like this.

I found something and it's works here is the code.

```
  $('#slideshow').on('thumbClick.desoslide', function(e) {
    console.log($(e.currentTarget).find('img').prop('alt'));
  });
```

So it's ok now
