### ISSUE TITLE
Slider doesn't show

### ISSUE THREAD

**Issue by jkoopman93** [sylouuu/desoslide#34]
Hello!

First of all: I really love the functions in your slider!

I've been working with a friend on my portfolio website and I wanted to have small thumbnails, which you could click to show a larger image. All of this worked with your slider. But I have a problem now; when I open a project page it shows the small thumbnails, but not the larger image. The larger image will only show up when I refresh the page. Maybe we did something wrong or do you have any ideas how to fix this? You can take a look here: http://jochemkoopman.nl/wip/work.html 
When you click for example on the first image you'll probably see what happens. It happens not only at my laptop, browser or what so ever, but at multiple laptops and browsers.

I hope to hear from you soon!

**Comment by sylouuu** [comment]
Hello @jkoopman93,

Welcome to GitHub as it seems that you have registered only for this question and thanks for your words.

This is weird as you created your portfolio, I don't know why but, after clicking on a card, I can't see `jquery.desoslide.min.js` and `jochem.js` files loaded.

When I refresh, they are loaded.

You should take a look around this.

Bests

**Comment by jkoopman93** [comment]
Hey @sylouuu !

Thank you for the (really!) quick response! You helped me along the way to finding the problem. :) 

I placed all my jQuery scripts at the bottom of my index.html (which I used for all my portfolio pages). I also editted in jochem.js (which I used to control the desoslider)
$(window).load(function() {         >       $(window).ready(function() {

Individually the changes didn't do anything, but together it worked.

**Comment by sylouuu** [comment]
So is this fixed? :)

**Comment by jkoopman93** [comment]
Yes! :)

**Comment by sylouuu** [comment]
Glad it's OK for you!
